spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useCursorFetch=true&rewriteBatchedStatements=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.splatter0.batch.support.KafkaStringOrByteDeserializer
      group-id: test
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.splatter0.batch.support.KafkaStringOrByteSerializer