spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useCursorFetch=true&rewriteBatchedStatements=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: dev
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer